import {Data,Product,applyCommand,emptyData,uid} from './model';
export function createDemo():Data {
 let d=emptyData();const offset=(n:number)=>{const dt=new Date();dt.setDate(dt.getDate()+n);return dt.toISOString().slice(0,10)};
 d.tenants=[{id:'demo',name:'صيدلية الحياة',owner:'د. أحمد علي',phone:'07700000000',address:'بغداد • المنصور',active:true,expires:offset(180)}];
 d.members=[{id:'owner',name:'د. أحمد علي',email:'owner@example.com',role:'owner',tenant_id:'demo'},{id:'sales',name:'سارة محمد',email:'sales@example.com',role:'sales',tenant_id:'demo'}];
 d.suppliers=[{id:'s1',name:'شركة الشفاء للأدوية',contact:'محمد حسن',phone:'07700000001',address:'بغداد • الكرادة',terms:30},{id:'s2',name:'مذخر النور الطبي',contact:'علي كريم',phone:'07700000002',address:'بغداد • الحارثية',terms:45},{id:'s3',name:'شركة الحياة فارما',contact:'حيدر أحمد',phone:'07700000003',address:'أربيل • شارع 100',terms:30}];
 const names=[['باراسيتامول','Paracetamol','مسكنات','500 mg','أقراص'],['فيتامين سي','Vitamin C','فيتامينات','1000 mg','أقراص'],['محلول ملحي','Sodium chloride','مستلزمات','0.9%','قنينة'],['واقي الشمس','Sun care','عناية بالبشرة','50 ml','كريم'],['شاش طبي معقم','Sterile gauze','مستلزمات','10 × 10 cm','عبوة'],['فيتامين د','Vitamin D','فيتامينات','1000 IU','كبسول'],['كريم مرطب','Moisturizing cream','عناية بالبشرة','100 ml','كريم'],['لاصق طبي','Medical tape','مستلزمات','5 cm','عبوة']];
 d.products=names.map((x,i)=>({id:'p'+i,name:x[0],scientific:x[1],barcode:'62910000000'+i,category:x[2],strength:x[3],form:x[4],manufacturer:['شركة ألف','شركة باء','شركة جيم'][i%3],country:'حسب العبوة',location:'A-'+(i+1),carton_boxes:20,box_strips:i%3===0?3:1,strip_units:i%3===0?10:1,base_unit:i%3===0?'حبة':'قطعة',sell_unit:i%3===0?250:3500+i*500,sell_strip:i%3===0?2500:3500+i*500,sell_box:i%3===0?7000:3500+i*500,sell_carton:i%3===0?130000:(3500+i*500)*18,min_stock:i%3===0?300:15,notes:''} as Product));
 for(let i=0;i<8;i++){const line={product_id:'p'+i,batch_no:'BT-2026-'+(101+i),production:offset(-120),expiry:offset(i===1?22:i===5?65:360),cartons:i===4?0:2,boxes:i===4?4:0,strips:0,units:0,bonus:0,carton_cost:i%3===0?80000:40000+i*6000,discount:0};d=applyCommand(d,{action:'purchase',request_id:uid(),payload:{number:'PUR-'+(202601+i),supplier_id:'s'+(i%3+1),date:offset(-25+i),due:offset(i===0?-3:8+i*3),attachment:'',lines:[line]}},'owner');}
 for(let i=0;i<7;i++){for(let k=0;k<3;k++){d=applyCommand(d,{action:'sale',request_id:uid(),payload:{customer:['زبون نقدي','محمد علي','نور أحمد'][k],method:k===1?'بطاقة':'نقدي',discount:0,lines:[{product_id:'p'+((i+k)%4),unit:'box',quantity:1}]}},'owner',k%2?'سارة محمد':'د. أحمد علي');d.sales[d.sales.length-1].date=offset(-6+i)+'T11:00:00Z';}}
 for(const p of d.purchases.slice(0,4)){d=applyCommand(d,{action:'payment',request_id:uid(),payload:{purchase_id:p.id,amount:p.total*.5,date:offset(-5),receipt:'RC-'+p.number,receipt_date:offset(-5),method:'نقدي',attachment:'',notes:'دفعة على الحساب'}},'owner');}
 return d;
}
