const DEFAULT_SUPABASE_URL='https://ihkrmzofpkrlwdlvorzi.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY='sb_publishable_4CIFEceT9Rc6v8YcKygZyw_8aWaROlb';

export function config(){const e=process.env;return {url:e.SUPABASE_URL||e.NEXT_PUBLIC_SUPABASE_URL||DEFAULT_SUPABASE_URL,key:e.SUPABASE_PUBLISHABLE_KEY||e.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||DEFAULT_SUPABASE_PUBLISHABLE_KEY,secret:e.SUPABASE_SECRET_KEY||e.SUPABASE_SERVICE_ROLE_KEY||''}}
export async function connectionStatus(){const c=config();if(!c.url||!c.key)return {configured:false,connected:false,error:'بيانات الاتصال غير مكتملة'};try{const r=await fetch(c.url+'/auth/v1/settings',{headers:{apikey:c.key},cache:'no-store'});if(!r.ok)return {configured:true,connected:false,error:'رفض Supabase بيانات الاتصال'};return {configured:true,connected:true,projectRef:new URL(c.url).hostname.split('.')[0]}}catch{return {configured:true,connected:false,error:'تعذر الوصول إلى Supabase'}}}
export async function supabase(path:string,init:RequestInit={},token?:string,admin=false){const c=config();if(!c.url||!c.key)throw Error('لم يتم إعداد اتصال Supabase بعد');const key=admin?c.secret:c.key;if(!key)throw Error('مفتاح إدارة الحسابات غير مهيأ على الخادم');const r=await fetch(c.url+path,{...init,headers:{apikey:key,...((admin||token)?{Authorization:'Bearer '+(admin?key:token)}:{}),'Content-Type':'application/json',...init.headers}});const text=await r.text();let result:any;try{result=text?JSON.parse(text):null}catch{throw Error('تعذر الاتصال بقاعدة البيانات')}if(!r.ok)throw Error(result?.msg||result?.message||result?.error_description||result?.error||'تعذر تنفيذ الطلب');return result;}
export function tokenFrom(req:Request){return req.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('pharmacy_access='))?.slice('pharmacy_access='.length)||''}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(process.env.APP_ORIGIN||req.url).origin)throw Error('طلب غير مسموح');}
export async function session(req:Request){const token=tokenFrom(req);if(!token)throw Error('يرجى تسجيل الدخول');const user=await supabase('/auth/v1/user',{},token);const profiles=await supabase('/rest/v1/pharmacy_members?id=eq.'+user.id+'&select=*',{},token);const profile=profiles?.[0];if(!profile)throw Error('الحساب غير مربوط بصيدلية');return {token,profile,user}}
export async function snapshot(req:Request){const {token,profile}=await session(req);const data=await supabase('/rest/v1/rpc/pharmacy_snapshot',{method:'POST',body:'{}'},token);return {data,profile}}
export function failure(e:unknown,status=400){return Response.json({error:e instanceof Error?e.message:'حدث خطأ غير متوقع'},{status,headers:{'Cache-Control':'no-store'}})}
