process.on('uncaughtException',e=>{console.error('FAIL:',e.message,e.where||'');process.exit(1)});
// Local PostgreSQL compatibility/security test. Run with PGLITE_MODULE pointing to a test-only installation.
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema auth;create schema storage;
create table auth.users(id uuid primary key,email text);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid,name text,bucket_id text);alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
await db.exec(readFileSync(new URL('../database/pharmacy-schema.sql',import.meta.url),'utf8'));
console.log('PASS: complete schema compiles on PostgreSQL');
const admin='10000000-0000-4000-8000-000000000001',owner='10000000-0000-4000-8000-000000000002',seller='10000000-0000-4000-8000-000000000003',other='10000000-0000-4000-8000-000000000004';
const tenant='20000000-0000-4000-8000-000000000001',tenant2='20000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values('${admin}','admin@example.com'),('${owner}','owner@example.com'),('${seller}','seller@example.com'),('${other}','other@example.com');
insert into public.pharmacy_tenants(id,name,owner,expires) values('${tenant}','Test','Owner','2099-01-01'),('${tenant2}','Other','Other','2099-01-01');
insert into public.pharmacy_members values('${admin}','Admin','admin@example.com','superadmin',null),('${owner}','Owner','owner@example.com','owner','${tenant}'),('${seller}','Seller','seller@example.com','sales','${tenant}'),('${other}','Other','other@example.com','owner','${tenant2}');`);
const asUser=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated')};
const command=async(action,payload,request=crypto.randomUUID())=>(await db.query('select public.pharmacy_command($1,$2::jsonb,$3::uuid) as x',[action,JSON.stringify(payload),request])).rows[0].x;
const snapshot=async()=>(await db.query('select public.pharmacy_snapshot() as x')).rows[0].x;
const expectError=async(fn)=>{let failed=false;try{await fn()}catch{failed=true}assert.equal(failed,true)};
await asUser(owner);
const product=(await command('product',{name:'Test drug',scientific:'Test',barcode:'123',category:'Test',form:'tablet',strength:'',manufacturer:'',country:'',location:'',carton_boxes:20,box_strips:3,strip_units:10,base_unit:'tablet',sell_unit:250,sell_strip:2500,sell_box:7000,sell_carton:130000,min_stock:10,notes:''})).id;
const supplier=(await command('supplier',{name:'Supplier',phone:'',contact:'',address:'',terms:30})).id;
const purchasePayload={number:'P1',supplier_id:supplier,date:'2026-01-01',due:'2026-12-01',attachment:'',lines:[{product_id:product,batch_no:'B1',production:'2025-01-01',expiry:'2095-01-01',cartons:1,boxes:0,strips:0,units:0,bonus:60,carton_cost:300000,discount:0}]};
const req=crypto.randomUUID();const purchase=(await command('purchase',purchasePayload,req)).id;
await command('purchase',purchasePayload,req);
let data=await snapshot();assert.equal(data.purchases.length,1);assert.equal(data.batches[0].quantity,660);assert.equal(data.purchases[0].total,300000);assert.ok(Math.abs(data.batches[0].unit_cost-300000/660)<.00001);
console.log('PASS: purchase conversions, cost, bonus and request idempotency');
await command('purchase',{...purchasePayload,number:'P2',lines:[{...purchasePayload.lines[0],expiry:'2090-01-01',batch_no:'B2',bonus:0}]});
const saleReq=crypto.randomUUID();await command('sale',{lines:[{product_id:product,unit:'strip',quantity:1}],discount:0,method:'نقدي'},saleReq);
data=await snapshot();assert.equal(data.batches.find(b=>b.batch_no==='B1').quantity,660);assert.equal(data.batches.find(b=>b.batch_no==='B2').quantity,590);
console.log('PASS: FEFO stock allocation');
const before=JSON.stringify(await snapshot());
await expectError(()=>command('sale',{lines:[{product_id:product,unit:'unit',quantity:1},{product_id:product,unit:'carton',quantity:100}],discount:0,method:'نقدي'}));assert.equal(JSON.stringify(await snapshot()),before);
console.log('PASS: failed multi-line sale rolls back all inventory and movements');
await command('payment',{purchase_id:purchase,amount:200000,date:'2026-09-09',receipt:'R1',receipt_date:'2026-09-09',method:'نقدي'});
await expectError(()=>command('payment',{purchase_id:purchase,amount:200000,date:'2026-09-09',receipt:'R2',receipt_date:'2026-09-09',method:'نقدي'}));
console.log('PASS: supplier overpayment rejected');
await asUser(seller);data=await snapshot();assert.equal(data.purchases.length,0);assert.equal(data.payments.length,0);assert.ok(data.batches.every(b=>!('unit_cost' in b)));assert.equal((await db.query('select * from public.pharmacy_batch_costs')).rows.length,0);
await expectError(()=>db.exec('update public.pharmacy_batches set quantity=0'));
await expectError(()=>command('supplier',{name:'Bad'}));await expectError(()=>command('sale',{lines:[{product_id:product,unit:'unit',quantity:1}],discount:1,method:'نقدي'}));
await command('sale',{lines:[{product_id:product,unit:'unit',quantity:1}],discount:0,method:'نقدي'});
console.log('PASS: sales role can sell, cannot access costs, purchase, directly modify stock or discount');
await asUser(other);data=await snapshot();assert.equal(data.products.length,0);assert.equal(data.batches.length,0);await expectError(()=>command('sale',{lines:[{product_id:product,unit:'unit',quantity:1}],discount:0,method:'نقدي'}));
console.log('PASS: tenant isolation and cross-tenant references rejected');
await asUser(admin);await command('tenant_status',{id:tenant});data=await snapshot();assert.equal(data.products.length,0);assert.equal(data.tenants.length,2);
await asUser(owner);await expectError(snapshot);await expectError(()=>command('supplier',{name:'Disabled',terms:0}));
console.log('PASS: superadmin metadata access and suspended pharmacy enforcement');
await db.close();
