import assert from 'node:assert/strict';
import {test} from 'node:test';
import {applyCommand,emptyData,uid,factors,stock,today} from '../lib/pharmacy/model.ts';
const product={name:'Test',scientific:'Test',barcode:'123',category:'Test',form:'tablet',strength:'',manufacturer:'',country:'',location:'',carton_boxes:20,box_strips:3,strip_units:10,base_unit:'tablet',sell_unit:250,sell_strip:2500,sell_box:7000,sell_carton:130000,min_stock:10,notes:''};
const cmd=(d:any,action:string,payload:any,role:any='owner')=>applyCommand(d,{action,payload,request_id:uid()},role);
function fixture(){let d=cmd(emptyData(),'product',product);d=cmd(d,'supplier',{name:'Supplier',phone:'',contact:'',address:'',terms:30});return d}
function buy(d:any,expiry='2035-01-01',extra={}){return cmd(d,'purchase',{number:uid(),supplier_id:d.suppliers[0].id,date:today(),due:today(),attachment:'',lines:[{product_id:d.products[0].id,batch_no:uid(),production:'2025-01-01',expiry,cartons:1,boxes:0,strips:0,units:0,bonus:0,carton_cost:300000,discount:0,...extra}]})}
test('pack conversion and bonus spread actual purchase cost',()=>{let d=fixture();d=buy(d,undefined,{bonus:60});assert.equal(factors(d.products[0]).carton,600);assert.equal(d.batches[0].quantity,660);assert.equal(d.purchases[0].total,300000);assert.ok(Math.abs(d.batches[0].unit_cost!-300000/660)<1e-8)});
test('sale consumes earliest-expiring batches even when received later',()=>{let d=buy(fixture(),'2035-01-01');d=buy(d,'2030-01-01');const original=d.batches[0].quantity;d=cmd(d,'sale',{lines:[{product_id:d.products[0].id,quantity:1,unit:'strip'}],discount:0});assert.equal(d.batches[0].quantity,original);assert.equal(d.batches[1].quantity,590);assert.equal(d.sales[0].total,2500)});
test('failed multi-line sale leaves stock and records unchanged',()=>{let d=buy(fixture());const before=JSON.stringify(d);assert.throws(()=>cmd(d,'sale',{discount:0,lines:[{product_id:d.products[0].id,quantity:1,unit:'box'},{product_id:d.products[0].id,quantity:500,unit:'carton'}]}));assert.equal(JSON.stringify(d),before)});
test('expired inventory cannot be sold',()=>{let d=buy(fixture());d.batches[0].expiry='2020-01-01';assert.equal(stock(d,d.products[0].id,true),0);assert.throws(()=>cmd(d,'sale',{discount:0,lines:[{product_id:d.products[0].id,quantity:1,unit:'unit'}]}))});
test('supplier payments reject overpayment and duplicate receipts',()=>{let d=buy(fixture());const p={purchase_id:d.purchases[0].id,amount:200000,date:today(),receipt:'r1',receipt_date:today(),method:'نقدي',attachment:''};d=cmd(d,'payment',p);assert.throws(()=>cmd(d,'payment',{...p,receipt:'r2'}));assert.throws(()=>cmd(d,'payment',{...p,amount:1000}));assert.equal(d.payments.length,1)});
test('sales staff cannot purchase or discount and negative stock is blocked',()=>{let d=buy(fixture());assert.throws(()=>cmd(d,'supplier',{name:'No'},'sales'));assert.throws(()=>cmd(d,'sale',{discount:1,lines:[{product_id:d.products[0].id,quantity:1,unit:'unit'}]},'sales'));assert.throws(()=>cmd(d,'adjust',{batch_id:d.batches[0].id,quantity:-1000,reason:'test'}))});
